### ISSUE TITLE
Google Fact Check Tools

### ISSUE THREAD

**Issue by MartinoMensio** [hearvox/unreliable-news#1]
Hi,
I just found your repo very interesting! You may consider also as "fact checking aggregator" the Google Fact Check Tools https://toolbox.google.com/factcheck/about

**Comment by hearvox** [comment]
Martino, just noticed your note. Checking Fact Check Explorer out now. Thanks much for the suggestion.

**Comment by MartinoMensio** [comment]
You're welcome! :)

**Comment by hearvox** [comment]
Just added FCE to:
https://github.com/hearvox/unreliable-news/edit/master/ref/apis-for-fact-checking.md

once I get access approval from Google, I may add more details.
